import { Drawer, styled, Theme, useMediaQuery, useTheme } from '@mui/material';
import { StyledProps } from './types';


const StyledDrawer = styled(Drawer)`
	position: relative;
	width: 25vw;
	height: 100vh;

	// this is a autogenerated media query
	// https://www.w3schools.com/css/css_rwd_mediaqueries.asp
	// allows us to use different styling based on screen size
	// here, it allows us to style everything up to 'medium' screens (ie. mobile)
	${({ theme }: StyledProps) => `${theme.breakpoints.down('md')}`} {
		width: 100vw;
	}
	
	.MuiDrawer-paper {
		box-sizing: border-box;

		position: absolute;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
	}
`;


function Sidebar() {
	const theme = useTheme();
	const isMobile = useMediaQuery(theme.breakpoints.down('md'));

	return (
		<>
			<StyledDrawer
				variant={isMobile? 'temporary' : 'permanent'}
			/>

		</>
	);
}

export default Sidebar;
